/**
 * Re-exports from centralised tunables for backwards-compatible imports.
 */
export {
  REFERENCE_QUANTITY,
  MULTI_MODEL_OVERHEAD,
  DEMAND_NOISE_MIN,
  DEMAND_NOISE_MAX,
  MIN_BATCH_SIZE,
  MAX_PRICE_MULTIPLIER,
  ASSEMBLY_QA_COST,
  PACKAGING_LOGISTICS_COST,
  CHANNEL_MARGIN_RATE,
  SUPPORT_BUDGET_MIN,
  SUPPORT_BUDGET_MAX,
  TOOLING_COST,
  CERTIFICATION_COST,
} from "../../../simulation/tunables";
